"""
Institutional figure layer for BRAVO Lab.

This module builds publication-ready Matplotlib figures from the processed CSV
outputs generated by the BRAVO Lab pipeline.

The goal is not decoration. The goal is visual evidence:

- performance path
- drawdown path
- BSTI stress signal
- BSTI policy behavior
- transition persistence
- calibration comparison
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter


DEFAULT_PROCESSED_DIR = Path("data/processed")
DEFAULT_FIGURES_DIR = Path("reports/figures")


def _setup_axes(ax, title: str, subtitle: str | None = None) -> None:
    ax.set_title(title, loc="left", fontsize=13, fontweight="bold", pad=14)

    if subtitle:
        ax.text(
            0.0,
            1.02,
            subtitle,
            transform=ax.transAxes,
            fontsize=9,
            alpha=0.75,
            ha="left",
            va="bottom",
        )

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(True, axis="y", alpha=0.25)
    ax.tick_params(axis="both", labelsize=9)


def _save_figure(fig, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=220, bbox_inches="tight")
    plt.close(fig)
    return path


def _read_csv(path: Path, index_col: int | None = 0) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()

    try:
        data = pd.read_csv(path, index_col=index_col)
    except Exception:
        return pd.DataFrame()

    if data.empty:
        return data

    try:
        data.index = pd.to_datetime(data.index)
    except Exception:
        pass

    return data


def _cumulative_returns(returns: pd.DataFrame) -> pd.DataFrame:
    return (1.0 + returns.fillna(0.0)).cumprod() - 1.0


def _drawdown(returns: pd.DataFrame) -> pd.DataFrame:
    cumulative = (1.0 + returns.fillna(0.0)).cumprod()
    running_peak = cumulative.cummax()
    return cumulative / running_peak - 1.0


def build_cumulative_performance_figure(
    processed_dir: Path,
    figures_dir: Path,
) -> Path | None:
    data = _read_csv(processed_dir / "bsti_policy_overlay_returns.csv")

    if data.empty:
        data = _read_csv(processed_dir / "overlay_return_table.csv")

    if data.empty:
        return None

    preferred = [
        "passive_brazil_equity",
        "covered_call",
        "collar",
        "stress_aware_overlay",
        "bsti_policy_overlay",
    ]

    columns = [col for col in preferred if col in data.columns]

    if not columns:
        numeric = data.select_dtypes(include=[np.number])
        columns = list(numeric.columns[:5])

    if not columns:
        return None

    cumulative = _cumulative_returns(data[columns])

    label_map = {
        "passive_brazil_equity": "Passive Brazil equity",
        "covered_call": "Covered call",
        "collar": "Collar",
        "stress_aware_overlay": "Stress-aware overlay",
        "bsti_policy_overlay": "BSTI policy overlay",
    }

    fig, ax = plt.subplots(figsize=(11.5, 6.5))

    for col in columns:
        ax.plot(
            cumulative.index,
            cumulative[col],
            linewidth=2.0,
            label=label_map.get(col, col.replace("_", " ").title()),
        )

    _setup_axes(
        ax,
        "Cumulative performance across overlay strategies",
        "Growth path from strategy return series. Higher lines indicate stronger cumulative performance.",
    )

    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.legend(frameon=False, fontsize=9, loc="best")

    return _save_figure(fig, figures_dir / "01_cumulative_performance.png")


def build_drawdown_figure(
    processed_dir: Path,
    figures_dir: Path,
) -> Path | None:
    data = _read_csv(processed_dir / "bsti_policy_overlay_returns.csv")

    if data.empty:
        data = _read_csv(processed_dir / "overlay_return_table.csv")

    if data.empty:
        return None

    preferred = [
        "passive_brazil_equity",
        "collar",
        "stress_aware_overlay",
        "bsti_policy_overlay",
    ]

    columns = [col for col in preferred if col in data.columns]

    if not columns:
        numeric = data.select_dtypes(include=[np.number])
        columns = list(numeric.columns[:4])

    if not columns:
        return None

    drawdown = _drawdown(data[columns])

    label_map = {
        "passive_brazil_equity": "Passive Brazil equity",
        "collar": "Collar",
        "stress_aware_overlay": "Stress-aware overlay",
        "bsti_policy_overlay": "BSTI policy overlay",
    }

    fig, ax = plt.subplots(figsize=(11.5, 6.2))

    for col in columns:
        ax.plot(
            drawdown.index,
            drawdown[col],
            linewidth=1.9,
            label=label_map.get(col, col.replace("_", " ").title()),
        )

    _setup_axes(
        ax,
        "Drawdown profile by strategy",
        "Peak-to-trough losses from each strategy path. Shallower drawdowns indicate stronger downside control.",
    )

    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.legend(frameon=False, fontsize=9, loc="lower left")

    return _save_figure(fig, figures_dir / "02_drawdown_profile.png")


def build_bsti_signal_figure(
    processed_dir: Path,
    figures_dir: Path,
) -> Path | None:
    data = _read_csv(processed_dir / "brazil_stress_transmission_index.csv")

    if data.empty or "bsti_0_100" not in data.columns:
        return None

    fig, ax = plt.subplots(figsize=(11.5, 6.2))

    ax.plot(
        data.index,
        data["bsti_0_100"],
        linewidth=2.0,
        label="BSTI",
    )

    ax.axhline(15.0, linewidth=1.2, linestyle="--", alpha=0.7, label="Warning threshold")
    ax.axhline(33.0, linewidth=1.2, linestyle="--", alpha=0.7, label="Stress threshold")

    _setup_axes(
        ax,
        "Brazil Stress Transmission Index",
        "Composite stress score from local risk, FX/VIX pressure, global risk, and external Brazil signals.",
    )

    ax.set_ylabel("BSTI score, 0 to 100", fontsize=9)
    ax.legend(frameon=False, fontsize=9, loc="best")

    return _save_figure(fig, figures_dir / "03_bsti_signal.png")


def build_bsti_policy_selection_figure(
    processed_dir: Path,
    figures_dir: Path,
) -> Path | None:
    data = _read_csv(
        processed_dir / "bsti_policy_selection_summary.csv",
        index_col=None,
    )

    if data.empty or "selected_strategy" not in data.columns or "share" not in data.columns:
        return None

    data = data.sort_values("share", ascending=True)

    fig, ax = plt.subplots(figsize=(10.5, 5.8))

    labels = data["selected_strategy"].str.replace("_", " ", regex=False).str.title()
    ax.barh(labels, data["share"])

    _setup_axes(
        ax,
        "BSTI policy-selection mix",
        "Share of observations assigned to each portfolio action by the BSTI policy rule.",
    )

    ax.xaxis.set_major_formatter(PercentFormatter(1.0))
    ax.set_xlabel("Share of policy observations", fontsize=9)

    return _save_figure(fig, figures_dir / "04_bsti_policy_selection_mix.png")


def build_bsti_transition_matrix_figure(
    processed_dir: Path,
    figures_dir: Path,
) -> Path | None:
    data = _read_csv(
        processed_dir / "bsti_transition_matrix.csv",
        index_col=None,
    )

    if data.empty:
        return None

    required = {"from_state", "to_state", "probability"}

    if not required.issubset(data.columns):
        return None

    pivot = data.pivot_table(
        index="from_state",
        columns="to_state",
        values="probability",
        fill_value=0.0,
    )

    state_order = [state for state in ["normal", "warning", "stress"] if state in pivot.index or state in pivot.columns]
    pivot = pivot.reindex(index=state_order, columns=state_order, fill_value=0.0)

    fig, ax = plt.subplots(figsize=(7.8, 6.2))

    image = ax.imshow(pivot.values, aspect="auto", vmin=0.0, vmax=1.0)

    ax.set_xticks(np.arange(len(pivot.columns)))
    ax.set_yticks(np.arange(len(pivot.index)))
    ax.set_xticklabels([str(x).title() for x in pivot.columns])
    ax.set_yticklabels([str(x).title() for x in pivot.index])

    for i in range(pivot.shape[0]):
        for j in range(pivot.shape[1]):
            ax.text(
                j,
                i,
                f"{pivot.values[i, j]:.0%}",
                ha="center",
                va="center",
                fontsize=10,
                fontweight="bold",
            )

    _setup_axes(
        ax,
        "BSTI state-transition matrix",
        "Probability of moving from one governance state to another in the next observation.",
    )

    ax.set_xlabel("To state", fontsize=9)
    ax.set_ylabel("From state", fontsize=9)

    colorbar = fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)
    colorbar.ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    colorbar.ax.tick_params(labelsize=8)

    return _save_figure(fig, figures_dir / "05_bsti_transition_matrix.png")


def build_bsti_calibration_figure(
    processed_dir: Path,
    figures_dir: Path,
) -> Path | None:
    data = _read_csv(
        processed_dir / "bsti_best_calibration_by_horizon.csv",
        index_col=None,
    )

    if data.empty:
        data = _read_csv(
            processed_dir / "bsti_calibration_grid.csv",
            index_col=None,
        )

    if data.empty:
        return None

    required = {"horizon_days", "weight_scheme", "governance_score"}

    if not required.issubset(data.columns):
        return None

    data = data.sort_values("governance_score", ascending=True).tail(10).copy()

    data["label"] = (
        data["weight_scheme"].astype(str)
        + " | "
        + data["horizon_days"].astype(str)
        + "d"
    )

    fig, ax = plt.subplots(figsize=(11, 6.2))

    ax.barh(data["label"], data["governance_score"])

    _setup_axes(
        ax,
        "Best BSTI calibration candidates",
        "Top scoring combinations of stress-channel weights, thresholds, and forward-risk horizon.",
    )

    ax.set_xlabel("Governance score", fontsize=9)

    return _save_figure(fig, figures_dir / "06_bsti_calibration_scores.png")


def build_report_figure_set(
    processed_dir: Path | str = DEFAULT_PROCESSED_DIR,
    figures_dir: Path | str = DEFAULT_FIGURES_DIR,
) -> dict[str, Path]:
    """
    Build all report figures and return paths by figure name.
    """
    processed_dir = Path(processed_dir)
    figures_dir = Path(figures_dir)

    builders = {
        "cumulative_performance": build_cumulative_performance_figure,
        "drawdown_profile": build_drawdown_figure,
        "bsti_signal": build_bsti_signal_figure,
        "bsti_policy_selection": build_bsti_policy_selection_figure,
        "bsti_transition_matrix": build_bsti_transition_matrix_figure,
        "bsti_calibration_scores": build_bsti_calibration_figure,
    }

    outputs: dict[str, Path] = {}

    for name, builder in builders.items():
        path = builder(processed_dir, figures_dir)

        if path is not None:
            outputs[name] = path

    return outputs


def figure_markdown_gallery(
    figure_paths: dict[str, Path],
) -> str:
    """
    Return markdown image links for the generated report figures.
    """
    if not figure_paths:
        return "No figure files were generated for this report run."

    titles = {
        "cumulative_performance": "Cumulative performance across overlay strategies",
        "drawdown_profile": "Drawdown profile by strategy",
        "bsti_signal": "Brazil Stress Transmission Index",
        "bsti_policy_selection": "BSTI policy-selection mix",
        "bsti_transition_matrix": "BSTI state-transition matrix",
        "bsti_calibration_scores": "Best BSTI calibration candidates",
    }

    lines = []

    for name, path in figure_paths.items():
        title = titles.get(name, name.replace("_", " ").title())
        relative_path = Path("figures") / path.name

        lines.append(f"### {title}")
        lines.append("")
        lines.append(f"![{title}]({relative_path.as_posix()})")
        lines.append("")

    return "\n".join(lines).strip()
